export declare const dayPickerButtonClassName = "justify-start pl-4 min-h-[38px]";
export declare const dayPickerCaptionClassName = "text-center h-9 flex items-center justify-center mx-9 capitalize mt-1";
export declare const dayPickerNavButtonPreviousClassName = "left-2 top-2";
export declare const dayPickerNavButtonNextClassName = "right-2 top-2";
export declare const dayPickerNavButtonClassName: string;
export declare const dayPickerHeadClassName = "text-xs dark:text-zinc-500";
export declare const dayPickerHeadCellClassName = "font-normal";
export declare const dayPickerDayClassName: string;
export declare const dayPickerDayRangeStartClassName: string;
export declare const dayPickerDaySelectedClassName: string;
export declare const dayPickerDayRangeEndClassName: string;
export declare const dayPickerTableClassName = "border-spacing-y-1 border-separate";
export declare const dayPickerCellClassName: string;
export declare const dayPickerDayOutsideClassName = "ui-date-picker-day-outside";
export declare const dayPickerDayRangeMiddleClassName = "ui-date-picker-day-range-middle";
export declare const dayPickerClassNames: {
    month_caption: string;
    button_previous: string;
    button_next: string;
    weekday: string;
    day_button: string;
    day: string;
    month_grid: string;
    range_start: string;
    selected: string;
    range_end: string;
    outside: string;
    range_middle: string;
};
