const intlPtBr = {
    "An user with the same email already exists": "Um usuário com o mesmo e-mail já existe",
    "Check your email inbox": "Verifique sua caixa de entrada de e-mail",
    Or: "Ou",
    "create a new account": "crie uma nova conta",
    "Create a new account": "Crie uma nova conta",
    "Click the link we sent you to create a new password": "Clique no link que enviamos para criar uma nova senha",
    "Did you remember your password?": "Você lembrou sua senha?",
    "Forgot your password?": "Esqueceu a senha?",
    "if you remembered the password": "se você lembrou sua senha",
    "It was not possible to create the user": "Não foi possível criar o usuário",
    "It was not possible to update the user": "Não foi possível atualizar o usuário",
    "New password": "Nova senha",
    "New user": "Novo usuário",
    "No records": "Nenhum resultado",
    Administrator: "Administrador",
    "Please fill with a valid email": "Por favor, preencher com um e-mail válido",
    "Please fill with an email": "Por favor, preencher com um e-mail",
    "Please fill with the new password": "Por favor, preencher com a nova senha",
    Email: "E-mail",
    Name: "Nome",
    "Please fill with your email": "Por favor, preencher com o seu e-mail",
    "Please fill with your password": "Por favor, preencher com a sua senha",
    "Reset password": "Redefinir senha",
    "Reset your password": "Redefinir sua senha",
    "Sign in": "Entrar",
    "Sign in to your account": "Entrar em sua conta",
    "sign in to your account": "entrar em sua conta",
    "Sign up": "Criar conta",
    "There was an unexpected error. Try again later.": "Ocorreu um erro inesperado. Tente novamente mais tarde.",
    "There was an unexpected error trying to list the users": "Ocorreu um erro inesperado tentando listar os usuários",
    "to your account": "na sua conta",
    "Try again": "Tentar novamente",
    "User not found or incorrect password": "Usuário não encontrado ou senha incorreta",
    "We sent a link to": "Nós enviamos um link para",
    "Your token expired. To generate a new one, make a new request to reset your password.": "Seu token expirou. Para gerar um novo, faça um novo pedido para redefinir sua senha.",
    Normal: "Normal",
    Password: "Senha",
    Save: "Salvar",
    Saved: "Salvo",
    Type: "Tipo",
    User: "Usuário",
    Users: "Usuários",
    "Created at": "Criado em",
    "Updated at": "Atualizado em",
    Click: "Clique",
    here: "aqui",
    "to sign in": "para entrar",
    New: "Novo",
    Disabled: "Desativado",
    "User is disabled": "Usuário está desativado",
    "User is enabled": "Usuário está ativo",
    Impersonate: "Assumir",
    "To reset your password click the link below": "Para redefinir sua senha clique no link abaixo",
    "Click here": "Clique aqui",
    "If you didn't request to reset your password, please ignore this email": "Se você não solicitou a redefinição de sua senha, ignore este e-mail",
    "Kind regards": "Atenciosamente",
    "or copy and paste the following link on your browser": "ou copie e cole o seguinte link no seu navegador",
    "We received a request to reset your password": "Recebemos uma solicitação para redefinir sua senha",
};
export default intlPtBr;
