import Image from "next/image";
import miyache from "./miyache.png";
import ticketis from "./ticketis.png";
import lapwing from "./lapwing.png";
import { GlobeAltIcon } from "@heroicons/react/24/outline";

export default function Projects() {
  return (
    <div className="mx-auto flex w-full max-w-screen-xl flex-col gap-10 px-4">
      <div className="flex flex-col gap-4">
        <div className="bg-gradient-to-br from-zinc-100 to-zinc-400 bg-clip-text font-dm text-5xl font-semibold tracking-[-2.88px] text-transparent">
          Some of our projects
        </div>
        <div className="max-w-[600px] font-dm text-2xl leading-8 tracking-[-1.44px] text-zinc-500">
          Some of the solutions we developed, combining design, technology and
          innovation to create incredible experiences!
        </div>
      </div>
      <div className="flex gap-6">
        <div className="flex flex-col gap-6">
          <div className="group relative overflow-hidden rounded-3xl">
            <Image
              src={miyache}
              alt="Miyache"
              className="h-full w-full object-cover"
            />
            <div className="absolute inset-0 bg-black bg-opacity-0 p-10 transition-all duration-300 ease-in-out group-hover:bg-opacity-85">
              <div className="flex h-full flex-col justify-end gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <div className="flex items-center gap-6">
                  <div className="font-dm text-3xl tracking-[-1.2px] text-white">
                    Miyache
                  </div>
                  <div className="rounded-full border border-zinc-700 bg-zinc-900 p-2">
                    <GlobeAltIcon className="h-5 w-5 text-white" />
                  </div>
                </div>
                <div className="font-dm text-lg leading-5 tracking-[-0.72px] text-zinc-400">
                  Miyache, a platform dedicated to limiting anime/discoveries
                  based on the users own choices, based on the ranking defined
                  by you, the system recommends new series to you.
                </div>
              </div>
            </div>
          </div>
          <div className="group relative overflow-hidden rounded-3xl">
            <Image
              src={ticketis}
              alt="Ticketis"
              className="h-full w-full object-cover"
            />
            <div className="absolute inset-0 bg-black bg-opacity-0 p-10 transition-all duration-300 ease-in-out group-hover:bg-opacity-85">
              <div className="flex h-full flex-col justify-end gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <div className="flex items-center gap-6">
                  <div className="font-dm text-3xl tracking-[-1.2px] text-white">
                    Ticketis
                  </div>
                  <div className="rounded-full border border-zinc-700 bg-zinc-900 p-2">
                    <GlobeAltIcon className="h-5 w-5 text-white" />
                  </div>
                </div>
                <div className="font-dm text-lg leading-5 tracking-[-0.72px] text-zinc-400">
                  Ticket sales platform for events in the city of Franca São
                  Paulo, Brazil
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="flex">
          <div className="group relative overflow-hidden rounded-3xl">
            <Image
              src={lapwing}
              alt="Lapwing"
              className="h-full w-full object-cover"
            />
            <div className="absolute inset-0 bg-black bg-opacity-0 p-10 transition-all duration-300 ease-in-out group-hover:bg-opacity-85">
              <div className="flex h-full flex-col justify-end gap-4 opacity-0 transition-opacity duration-300 group-hover:opacity-100">
                <div className="flex items-center gap-6">
                  <div className="font-dm text-3xl tracking-[-1.2px] text-white">
                    Lapwing
                  </div>
                  <div className="rounded-full border border-zinc-700 bg-zinc-900 p-2">
                    <GlobeAltIcon className="h-5 w-5 text-white" />
                  </div>
                </div>
                <div className="font-dm text-lg leading-5 tracking-[-0.72px] text-zinc-400">
                  Soccer matches generated by AI, creat players, teams and win
                  money with smart decisions
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
